### ISSUE TITLE
Add pre-commit with ruff + black

### ISSUE THREAD

**Issue by Ovsyanka83** [Ovsyanka83/universi#30]

**Comment by Aditi840** [comment]
@Ovsyanka83, I would like to work on this issue, just give me an overview on what needs to be done.

**Comment by Ovsyanka83** [comment]
We need to add a pre-commit file that will run ruff and black.

Note that both must use configurations from project.toml.

Let's leave out pyright for now. We'll just add it as a separate step in CI later because there are many issues with running it at pre-commit.

**Comment by Ovsyanka83** [comment]
I'm afraid @coffeewasmyidea did this much faster. I hope it's okay with you.

**Comment by Aditi840** [comment]
@Ovsyanka83, It's fine, let me know if you need help in another issue.
